// Generated by CoffeeScript 1.4.0
(function() {
  var Snippets,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Snippets = (function(_super) {

    __extends(Snippets, _super);

    Snippets.prototype.tag = 'li';

    function Snippets() {
      Snippets.__super__.constructor.apply(this, arguments);
      this.log('snippets_controller init');
      this.append("<a>" + this.item.name + "</a>");
    }

    Snippets.prototype.add = function() {
      var now;
      now = new Date();
      return Snippet.create({
        name: this.snippetName.val(),
        code: this.snippetCode.val(),
        description: this.snippetDescription.val(),
        timestamp: now.getTime()
      });
    };

    Snippets.prototype.reset = function() {
      this.snippetName.val('');
      this.snippetCode.val('');
      this.snippetDescription.val('');
      return this.log(Snippet.all());
    };

    return Snippets;

  })(Spine.Controller);

  this.Snippets = Snippets;

}).call(this);
