// Generated by CoffeeScript 1.4.0
(function() {

  Spine.Controller.include({
    xhr: function(para) {
      var async, data, ev, eventListener, h, header, method, uploadEventListener, url, xhr, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
      url = para.url;
      data = (_ref = para.data) != null ? _ref : '';
      async = (_ref1 = para.async) != null ? _ref1 : true;
      header = (_ref2 = para.header) != null ? _ref2 : {};
      method = (_ref3 = para.method) != null ? _ref3 : 'GET';
      eventListener = (_ref4 = para.eventListener) != null ? _ref4 : {};
      uploadEventListener = (_ref5 = para.uploadEventListener) != null ? _ref5 : {};
      xhr = new XMLHttpRequest();
      for (_i = 0, _len = eventListener.length; _i < _len; _i++) {
        ev = eventListener[_i];
        xhr.addEventListener(ev, eventListener[ev]);
      }
      for (_j = 0, _len1 = uploadEventListener.length; _j < _len1; _j++) {
        ev = uploadEventListener[_j];
        xhr.upload.addEventListener(ev, uploadEventListener[ev]);
      }
      xhr.open(method, url, async);
      for (_k = 0, _len2 = header.length; _k < _len2; _k++) {
        h = header[_k];
        xhr.setRequestHeader(h, header[h]);
      }
      xhr.send(data);
      return xhr.responseText;
    }
  });

}).call(this);
