// Generated by CoffeeScript 1.4.0
(function() {
  var SnippetCreate,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  SnippetCreate = (function(_super) {

    __extends(SnippetCreate, _super);

    SnippetCreate.prototype.tag = 'div';

    SnippetCreate.prototype.className = 'snippet-create';

    SnippetCreate.prototype.tpl = '#tpl-snippet-add';

    SnippetCreate.prototype.elements = {
      '.snippet-name input': 'snippetName',
      '.snippet-code textarea': 'snippetCode',
      '.snippet-description input': 'snippetDescription',
      '.snippet-list .list': 'snippetList'
    };

    SnippetCreate.prototype.events = {
      'click #action-add-snippet': 'create',
      'click #action-reset-snippet': 'reset',
      'click #action-del-all': 'deleteAll'
    };

    function SnippetCreate() {
      SnippetCreate.__super__.constructor.apply(this, arguments);
      this.el.append($(this.tpl).clone().html());
      this.refreshElements();
    }

    SnippetCreate.prototype.create = function() {
      var now;
      console.log('create');
      now = new Date();
      Snippet.create({
        name: this.snippetName.val(),
        code: this.snippetCode.val(),
        description: this.snippetDescription.val(),
        timestamp: now.getTime()
      });
      return this.navigate('/list');
    };

    SnippetCreate.prototype.deleteAll = function() {
      return console.log('deleteAll');
    };

    SnippetCreate.prototype.reset = function() {
      this.snippetName.val('');
      this.snippetCode.val('');
      return this.snippetDescription.val('');
    };

    return SnippetCreate;

  })(Spine.Controller);

  this.SnippetCreate = SnippetCreate;

}).call(this);
