// Generated by CoffeeScript 1.4.0
(function() {
  var Snippet, Spine,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Spine = this.Spine || require('spine');

  Snippet = (function(_super) {

    __extends(Snippet, _super);

    function Snippet() {
      return Snippet.__super__.constructor.apply(this, arguments);
    }

    Snippet.configure('Snippet', 'name', 'code', 'description', 'timestamp');

    Snippet.extend(Spine.Model.Local);

    return Snippet;

  })(Spine.Model);

  this.Snippet = Snippet;

}).call(this);
